// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "08034546789",
    name: "Mr. Adebayo O. Ayodele",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    subjects: ["Information Technology & Digital Skills", "Business & Management"],
    classes: ["Digital Marketing Specialist", "Entrepreneurship & Small Business Incubation", "Renewable Energy Technology Training"],
    address: "Wuse Zone 1, Federal Capital Territory, Abuja.",
  },
  {
    id: 2,
    teacherId: "08034546789",
    name: "Dr. Amina Garba",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    subjects: ["Technical & Vocational Trades", "Creative & Design"],
    classes: ["Professional Copywriting Course", "Graphic Design Masterclass", "Renewable Energy Technology Training"],
    address: "AMAC, Federal Capital Territory, Nigeria",
  },
  {
    id: 3,
    teacherId: "08034546789",
    name: "Mr. Abubakar S. Salihu",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    subjects: ["Voice Acting & Narration"],
    classes: ["Professional Copywriting Course", "Sales & Negotiation Skills Training", "Renewable Energy Technology Training"],
    address: "Central Business District, Abuja, Federal Capital Territory, Nigeria",
  },
  {
    id: 4,
    teacherId: "08034546789",
    name: "Dr. Titilayo Oluwafemi",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    subjects: ["Grant Writing for Non-Profits"],
    classes: ["Professional Copywriting Course", "Sales & Negotiation Skills Training", "Renewable Energy Technology Training"],
    address: "Maitama District, Federal Capital Territory, Abuja.",
  },
  {
    id: 5,
    teacherId: "08034546789",
    name: "Dr. Ngozi Chinedu",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    subjects: ["Leadership & Team Building", "Risk Management Professional"],
    classes: ["Professional Copywriting Course", "Sales & Negotiation Skills Training", "Renewable Energy Technology Training"],
    address: "Durumi District, Federal Capital Territory, Abuja.",
  },
  {
    id: 6,
    teacherId: "08034546789",
    name: "Dr. Nana Jallo",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    subjects: ["Technical & Vocational Trades"],
    classes: ["Professional Copywriting Course", "Sales & Negotiation Skills Training", "Renewable Energy Technology Training"],
    address: "Life Camp, Federal Capital Territory, Abuja.",
  },
  {
    id: 7,
    teacherId: "08034546789",
    name: "Dr. Eseoghene Ovie",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    subjects: ["Agriculture & Environmental Studies", "Tourism & Lifestyle"],
    classes: ["Professional Copywriting Course", "Sales & Negotiation Skills Training", "Renewable Energy Technology Training"],
    address: "Karmo District, Federal Capital Territory, Abuja.",
  },
  {
    id: 8,
    teacherId: "08034546789",
    name: "Dr. Eseoghene Ovie",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    subjects: ["Information Technology & Digital Skills", "Business & Management"],
    classes: ["Professional Copywriting Course", "Sales & Negotiation Skills Training", "Renewable Energy Technology Training"],
    address: "Galadimawa District, Federal Capital Territory, Abuja.",
  },
  {
    id: 9,
    teacherId: "08034546789",
    name: "Osagie Egharevba",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    subjects: ["Social Sciences & Humanities", "Health Sciences & Public Safety"],
    classes: ["Professional Copywriting Course", "Sales & Negotiation Skills Training", "Renewable Energy Technology Training"],
    address: "Lugbe, Federal Capital Territory, Abuja.",
  },
  {
    id: 10,
    teacherId: "08034546789",
    name: "Dr. Zara Biu",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    subjects: ["Agriculture & Food Production"],
    classes: ["Professional Copywriting Course", "Sales & Negotiation Skills Training", "Renewable Energy Technology Training"],
    address: "Abaji, A Local Government Area in the southern part of the FCT",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "08034546789",
    name: "Lami Abubakar",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    grade: "A",
    class: "Digital Marketing Specialist",
    address: "Gwagwalada, Federal Capital Territory, Abuja.",
  },
  {
    id: 2,
    studentId: "08034546789",
    name: "Daniel Kwaha",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    grade: "A",
    class: "Professional Copywriting Course",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 3,
    studentId: "08034546789",
    name: "Mary Thlama",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    grade: "B",
    class: "Professional Copywriting Course",
    address: "Nyanya, Federal Capital Territory, Abuja.",
  },
  {
    id: 4,
    studentId: "08034546789",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    grade: "B",
    class: "Professional Copywriting Course",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 5,
    studentId: "08034546789",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    grade: "C",
    class: "Professional Copywriting Course",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 6,
    studentId: "08034546789",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    grade: "F",
    class: "Professional Copywriting Course",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 7,
    studentId: "08034546789",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    grade: "F",
    class: "Professional Copywriting Course",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 8,
    studentId: "08034546789",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    grade: "A",
    class: "Professional Copywriting Course",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 9,
    studentId: "08034546789",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    grade: "D",
    class: "Professional Copywriting Course",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 10,
    studentId: "08034546789",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "08034546789",
    grade: "A",
    class: "Professional Copywriting Course",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Lami Abubakar",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "08034546789",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 2,
    name: "Daniel Kwaha",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "08034546789",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "08034546789",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "08034546789",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "08034546789",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "08034546789",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "08034546789",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "08034546789",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "08034546789",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "08034546789",
    address: "FCTA Secratariat, Kapital Street, Area 11, Garki, FCT, Nigeria",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Information Technology & Digital Skills",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "Strategic Planning & Execution",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Technical & Vocational Trades",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Creative & Design",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Agriculture & Food Production",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "Leadership & Team Building",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Leadership & Team Building",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Poultry Farming Management",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Social Sciences & Humanities",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Agriculture & Environmental Studies",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "Finance & Accounting",
    capacity: 20,
    grade: "A",
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "Business Administration & Strategy",
    capacity: 22,
    grade: "E",
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "Renewable Energy Technology Training",
    capacity: 20,
    grade: "A",
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "Sales & Negotiation Skills Training",
    capacity: 18,
    grade: "A",
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "Professional Copywriting Course",
    capacity: 16,
    grade: "B",
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "Entrepreneurship & Innovation",
    capacity: 20,
    grade: "D",
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "Foreign Language Proficiency",
    capacity: 18,
    grade: "A",
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "Legal & Paralegal Studies ",
    capacity: 22,
    grade: "A",
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "Public Policy & Administration",
    capacity: 18,
    grade: "C",
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "International Relations & Diplomacy",
    capacity: 20,
    grade: "B",
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Information Technology & Digital Skills",
    class: "Finance & Accounting",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "Digital Marketing Specialist",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "Professional Copywriting Course",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "Legal & Paralegal Studies ",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Technical & Vocational Trades",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Creative & Design",
    class: "Sales & Negotiation Skills Training",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Information Technology & Digital Skills",
    class: "Finance & Accounting",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "Digital Marketing Specialist",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "Professional Copywriting Course",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "Legal & Paralegal Studies ",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Technical & Vocational Trades",
    class: "Foreign Language Proficiency",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Creative & Design",
    class: "Corel Draw Masterclass",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Information Technology & Digital Skills",
    class: "Finance & Accounting",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "Digital Marketing Specialist",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "Professional Copywriting Course",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "Legal & Paralegal Studies ",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Technical & Vocational Trades",
    class: "Foreign Language Proficiency",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Creative & Design",
    class: "Corel Draw Masterclass",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Information Technology & Digital Skills",
    class: "Finance & Accounting",
    teacher: "Lami Abubakar",
    student: "Lami Abubakar",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Lami Abubakar",
    student: "Lami Abubakar",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Lami Abubakar",
    student: "Lami Abubakar",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "Digital Marketing Specialist",
    teacher: "Lami Abubakar",
    student: "Lami Abubakar",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Lami Abubakar",
    student: "Lami Abubakar",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "Professional Copywriting Course",
    teacher: "Lami Abubakar",
    student: "Lami Abubakar",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "Entrepreneurship & Small Business Incubation",
    teacher: "Lami Abubakar",
    student: "Lami Abubakar",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "Legal & Paralegal Studies ",
    teacher: "Lami Abubakar",
    student: "Lami Abubakar",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Technical & Vocational Trades",
    class: "Foreign Language Proficiency",
    teacher: "Lami Abubakar",
    student: "Lami Abubakar",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Creative & Design",
    class: "8A",
    teacher: "Lami Abubakar",
    student: "Lami Abubakar",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "Finance & Accounting",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "Entrepreneurship & Small Business Incubation",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "Entrepreneurship & Small Business Incubation",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "Entrepreneurship & Small Business Incubation",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "Professional Copywriting Course",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "Digital Marketing Specialist",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "Business Administration & Strategy",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "Corel Draw Masterclass",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "Sales & Negotiation Skills Training",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "Entrepreneurship & Innovation",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About Information Technology & Digital Skills Test",
    class: "Entrepreneurship & Small Business Incubation",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About  Information Technology & Digital Skills Test",
    class: "Entrepreneurship & Small Business Incubation",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About  Information Technology & Digital Skills Test",
    class: "Corel Draw Masterclass",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About  Information Technology & Digital Skills Test",
    class: "Entrepreneurship & Small Business Incubation",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About  Information Technology & Digital Skills Test",
    class: "Corel Draw Masterclass",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About Entrepreneurship & Small Business Incubation Information Technology & Digital Skills Test",
    class: "Entrepreneurship & Small Business Incubation",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About  Information Technology & Digital Skills Test",
    class: "Corel Draw Masterclass",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About Sales & Negotiation Skills Training Information Technology & Digital Skills Test",
    class: "Sales & Negotiation Skills Training",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About Renewable Energy Technology Training Information Technology & Digital Skills Test",
    class: "Renewable Energy Technology Training",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About Corel Draw Masterclass Information Technology & Digital Skills Test",
    class: "Corel Draw Masterclass",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Information Technology & Digital Skills",
    allDay: true,
    start: new Date(2024, 7, 12, 8, 0),
    end: new Date(2024, 7, 12, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "Agriculture & Food Production",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "Technical & Vocational Trades",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "Creative & Design",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "Agriculture & Food Production",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "Technical & Vocational Trades",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Information Technology & Digital Skills",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Agriculture & Food Production",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },

  {
    title: "Creative & Design",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Agriculture & Food Production",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Technical & Vocational Trades",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Information Technology & Digital Skills",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },

  {
    title: "Technical & Vocational Trades",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Creative & Design",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];